exclude: '^(thirdparty/|build/|\.vscode/|\.git/|.*\.cdef$|CMakeLists\.txt$)'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/crate-ci/typos
    rev: v1.35.4
    hooks:
      - id: typos

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
