name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        config: [Debug, Release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          else
            cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          fi

      - name: Build
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            cmake --build build --config ${{ matrix.config }}
          else
            cmake --build build -- -j$(nproc)
          fi

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.config }}-binaries
          path: |
            build/**/*.exe
            build/**/*.dll
            build/**/*.lib
            build/**/*.pdb
            build/**/*.so
            build/**/*.a
