name: Post-Merge

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  cleanup:
    name: Cache cleanup
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read

    steps:
      - name: Cleanup
        run: |
          echo "Fetching list of cache keys"
          cacheKeysForPR=$(gh cache list --ref $BRANCH --limit 100 --json id --jq '.[].id')

          set +e  # Setting this to not fail the workflow while deleting cache keys.
          echo "Deleting caches from $BRANCH:"
          for cacheKey in $cacheKeysForPR
          do
              echo " - $cacheKey"
              gh cache delete $cacheKey
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
